export interface Skill {
  id: string
  name: string
  description: string
  icon: string
  category: "fire" | "ice" | "combat" | "defense"
  state: "locked" | "available" | "unlocked" | "maxed"
  currentLevel: number
  maxLevel: number
  x: number
  y: number
  size: number
  shape: "hexagon" | "diamond" | "circle" | "square"
}

export interface Connection {
  from: string
  to: string
}

// Large skill tree data with multiple branches
export const skillsData: Skill[] = [
  // CENTER - Core skills
  {
    id: "core-1",
    name: "Inner Power",
    description: "Unlock your inner potential. This is the foundation of all other abilities.",
    icon: "⚡",
    category: "combat",
    state: "maxed",
    currentLevel: 5,
    maxLevel: 5,
    x: 1200,
    y: 900,
    size: 100,
    shape: "hexagon",
  },

  // FIRE BRANCH - Left side
  {
    id: "fire-1",
    name: "Ember Strike",
    description: "Infuse your attacks with fire, dealing additional burn damage over time.",
    icon: "🔥",
    category: "fire",
    state: "unlocked",
    currentLevel: 3,
    maxLevel: 5,
    x: 900,
    y: 800,
    size: 80,
    shape: "square",
  },
  {
    id: "fire-2",
    name: "Flame Shield",
    description: "Surround yourself with protective flames that damage nearby enemies.",
    icon: "🛡️",
    category: "fire",
    state: "unlocked",
    currentLevel: 2,
    maxLevel: 3,
    x: 700,
    y: 700,
    size: 70,
    shape: "diamond",
  },
  {
    id: "fire-3",
    name: "Inferno",
    description: "Unleash a devastating explosion of fire in a large area.",
    icon: "💥",
    category: "fire",
    state: "available",
    currentLevel: 0,
    maxLevel: 5,
    x: 500,
    y: 600,
    size: 90,
    shape: "hexagon",
  },
  {
    id: "fire-4",
    name: "Phoenix Rising",
    description: "Upon death, rise again with full health (once per battle).",
    icon: "🦅",
    category: "fire",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 300,
    y: 500,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "fire-5",
    name: "Burning Aura",
    description: "Passive fire aura that continuously damages nearby foes.",
    icon: "☀️",
    category: "fire",
    state: "available",
    currentLevel: 0,
    maxLevel: 3,
    x: 600,
    y: 850,
    size: 60,
    shape: "circle",
  },
  {
    id: "fire-6",
    name: "Molten Core",
    description: "Your fire spells have increased critical hit chance.",
    icon: "🌋",
    category: "fire",
    state: "locked",
    currentLevel: 0,
    maxLevel: 5,
    x: 400,
    y: 750,
    size: 65,
    shape: "diamond",
  },
  {
    id: "fire-7",
    name: "Ash Walker",
    description: "Move through flames unharmed and gain speed boost.",
    icon: "👣",
    category: "fire",
    state: "locked",
    currentLevel: 0,
    maxLevel: 2,
    x: 200,
    y: 650,
    size: 55,
    shape: "circle",
  },

  // ICE BRANCH - Right side
  {
    id: "ice-1",
    name: "Frost Bolt",
    description: "Launch a bolt of ice that slows and damages enemies.",
    icon: "❄️",
    category: "ice",
    state: "unlocked",
    currentLevel: 4,
    maxLevel: 5,
    x: 1500,
    y: 800,
    size: 80,
    shape: "square",
  },
  {
    id: "ice-2",
    name: "Ice Barrier",
    description: "Create a protective shield of ice that absorbs damage.",
    icon: "🧊",
    category: "ice",
    state: "unlocked",
    currentLevel: 2,
    maxLevel: 3,
    x: 1700,
    y: 700,
    size: 70,
    shape: "diamond",
  },
  {
    id: "ice-3",
    name: "Blizzard",
    description: "Summon a devastating blizzard that freezes all enemies.",
    icon: "🌨️",
    category: "ice",
    state: "available",
    currentLevel: 0,
    maxLevel: 5,
    x: 1900,
    y: 600,
    size: 90,
    shape: "hexagon",
  },
  {
    id: "ice-4",
    name: "Absolute Zero",
    description: "Flash freeze everything in range, dealing massive damage.",
    icon: "💎",
    category: "ice",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 2100,
    y: 500,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "ice-5",
    name: "Frozen Touch",
    description: "Your melee attacks have a chance to freeze targets.",
    icon: "✋",
    category: "ice",
    state: "available",
    currentLevel: 0,
    maxLevel: 3,
    x: 1800,
    y: 850,
    size: 60,
    shape: "circle",
  },
  {
    id: "ice-6",
    name: "Glacial Spike",
    description: "Impale enemies with spikes of pure ice.",
    icon: "🗡️",
    category: "ice",
    state: "locked",
    currentLevel: 0,
    maxLevel: 5,
    x: 2000,
    y: 750,
    size: 65,
    shape: "diamond",
  },
  {
    id: "ice-7",
    name: "Permafrost",
    description: "Permanently slow enemies in a radius around you.",
    icon: "🥶",
    category: "ice",
    state: "locked",
    currentLevel: 0,
    maxLevel: 2,
    x: 2200,
    y: 650,
    size: 55,
    shape: "circle",
  },

  // COMBAT BRANCH - Top
  {
    id: "combat-1",
    name: "Power Strike",
    description: "A devastating melee attack that deals triple damage.",
    icon: "⚔️",
    category: "combat",
    state: "unlocked",
    currentLevel: 3,
    maxLevel: 5,
    x: 1100,
    y: 600,
    size: 75,
    shape: "square",
  },
  {
    id: "combat-2",
    name: "Battle Fury",
    description: "Enter a rage state, increasing attack speed significantly.",
    icon: "😤",
    category: "combat",
    state: "available",
    currentLevel: 0,
    maxLevel: 3,
    x: 1000,
    y: 400,
    size: 70,
    shape: "diamond",
  },
  {
    id: "combat-3",
    name: "Whirlwind",
    description: "Spin in a deadly circle, hitting all nearby enemies.",
    icon: "🌀",
    category: "combat",
    state: "locked",
    currentLevel: 0,
    maxLevel: 5,
    x: 900,
    y: 250,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "combat-4",
    name: "Execution",
    description: "Instantly kill enemies below 20% health.",
    icon: "💀",
    category: "combat",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 800,
    y: 100,
    size: 80,
    shape: "hexagon",
  },
  {
    id: "combat-5",
    name: "Swift Blade",
    description: "Increase attack speed by 15% per level.",
    icon: "⚡",
    category: "combat",
    state: "unlocked",
    currentLevel: 2,
    maxLevel: 5,
    x: 1300,
    y: 600,
    size: 75,
    shape: "square",
  },
  {
    id: "combat-6",
    name: "Blade Storm",
    description: "Throw multiple blades in all directions.",
    icon: "🗡️",
    category: "combat",
    state: "available",
    currentLevel: 0,
    maxLevel: 3,
    x: 1400,
    y: 400,
    size: 70,
    shape: "diamond",
  },
  {
    id: "combat-7",
    name: "Cleave",
    description: "Your attacks hit multiple enemies at once.",
    icon: "🪓",
    category: "combat",
    state: "locked",
    currentLevel: 0,
    maxLevel: 5,
    x: 1500,
    y: 250,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "combat-8",
    name: "Berserker",
    description: "Deal more damage as your health decreases.",
    icon: "🔱",
    category: "combat",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 1600,
    y: 100,
    size: 80,
    shape: "hexagon",
  },

  // DEFENSE BRANCH - Bottom
  {
    id: "defense-1",
    name: "Iron Skin",
    description: "Increase your armor rating substantially.",
    icon: "🛡️",
    category: "defense",
    state: "unlocked",
    currentLevel: 4,
    maxLevel: 5,
    x: 1100,
    y: 1200,
    size: 75,
    shape: "square",
  },
  {
    id: "defense-2",
    name: "Regeneration",
    description: "Slowly recover health over time in combat.",
    icon: "💚",
    category: "defense",
    state: "available",
    currentLevel: 0,
    maxLevel: 5,
    x: 1000,
    y: 1400,
    size: 70,
    shape: "diamond",
  },
  {
    id: "defense-3",
    name: "Fortress",
    description: "Become immovable, gaining massive damage reduction.",
    icon: "🏰",
    category: "defense",
    state: "locked",
    currentLevel: 0,
    maxLevel: 3,
    x: 900,
    y: 1550,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "defense-4",
    name: "Immortality",
    description: "Survive fatal damage once, restored to 1 HP.",
    icon: "👼",
    category: "defense",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 800,
    y: 1700,
    size: 80,
    shape: "hexagon",
  },
  {
    id: "defense-5",
    name: "Vitality",
    description: "Increase maximum health by 10% per level.",
    icon: "❤️",
    category: "defense",
    state: "unlocked",
    currentLevel: 3,
    maxLevel: 5,
    x: 1300,
    y: 1200,
    size: 75,
    shape: "square",
  },
  {
    id: "defense-6",
    name: "Life Steal",
    description: "Recover health with each successful attack.",
    icon: "🩸",
    category: "defense",
    state: "available",
    currentLevel: 0,
    maxLevel: 5,
    x: 1400,
    y: 1400,
    size: 70,
    shape: "diamond",
  },
  {
    id: "defense-7",
    name: "Shield Wall",
    description: "Block all frontal attacks for a duration.",
    icon: "🧱",
    category: "defense",
    state: "locked",
    currentLevel: 0,
    maxLevel: 3,
    x: 1500,
    y: 1550,
    size: 85,
    shape: "hexagon",
  },
  {
    id: "defense-8",
    name: "Divine Protection",
    description: "Become invulnerable for 3 seconds.",
    icon: "✨",
    category: "defense",
    state: "locked",
    currentLevel: 0,
    maxLevel: 1,
    x: 1600,
    y: 1700,
    size: 80,
    shape: "hexagon",
  },
]

export const connectionsData: Connection[] = [
  // Core to branches
  { from: "core-1", to: "fire-1" },
  { from: "core-1", to: "ice-1" },
  { from: "core-1", to: "combat-1" },
  { from: "core-1", to: "combat-5" },
  { from: "core-1", to: "defense-1" },
  { from: "core-1", to: "defense-5" },

  // Fire branch
  { from: "fire-1", to: "fire-2" },
  { from: "fire-1", to: "fire-5" },
  { from: "fire-2", to: "fire-3" },
  { from: "fire-2", to: "fire-6" },
  { from: "fire-3", to: "fire-4" },
  { from: "fire-5", to: "fire-6" },
  { from: "fire-6", to: "fire-7" },
  { from: "fire-7", to: "fire-4" },

  // Ice branch
  { from: "ice-1", to: "ice-2" },
  { from: "ice-1", to: "ice-5" },
  { from: "ice-2", to: "ice-3" },
  { from: "ice-2", to: "ice-6" },
  { from: "ice-3", to: "ice-4" },
  { from: "ice-5", to: "ice-6" },
  { from: "ice-6", to: "ice-7" },
  { from: "ice-7", to: "ice-4" },

  // Combat branch
  { from: "combat-1", to: "combat-2" },
  { from: "combat-2", to: "combat-3" },
  { from: "combat-3", to: "combat-4" },
  { from: "combat-5", to: "combat-6" },
  { from: "combat-6", to: "combat-7" },
  { from: "combat-7", to: "combat-8" },
  { from: "combat-3", to: "combat-7" },

  // Defense branch
  { from: "defense-1", to: "defense-2" },
  { from: "defense-2", to: "defense-3" },
  { from: "defense-3", to: "defense-4" },
  { from: "defense-5", to: "defense-6" },
  { from: "defense-6", to: "defense-7" },
  { from: "defense-7", to: "defense-8" },
  { from: "defense-3", to: "defense-7" },
]
